/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.com;

/**
 *
 * @author TOR
 */
public class view_login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public view_login() {
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panel_background = new javax.swing.JPanel();
        panel_derecha = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        panel_login = new javax.swing.JPanel();
        label_usuario = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        Boton_iniciae_sesion = new javax.swing.JButton();
        label_IniciarSesion = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        panel_izquierda = new javax.swing.JPanel();
        panel_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setEnabled(false);
        background.setOpaque(false);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_derecha.setBackground(new java.awt.Color(242, 206, 211));

        panel_login.setForeground(java.awt.Color.lightGray);
        panel_login.setEnabled(false);
        panel_login.setOpaque(false);
        panel_login.setRequestFocusEnabled(false);
        panel_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_usuario.setText("Usuario");
        panel_login.add(label_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 96, -1, -1));

        label_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_password.setText("Contraseña");
        panel_login.add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        txt_usuario.setBackground(new java.awt.Color(243, 207, 212));
        txt_usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_usuario.setBorder(null);
        txt_usuario.setFocusCycleRoot(true);
        txt_usuario.setFocusTraversalPolicyProvider(true);
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        panel_login.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 230, 38));

        txt_password.setBackground(new java.awt.Color(243, 207, 212));
        txt_password.setBorder(null);
        txt_password.setFocusCycleRoot(true);
        txt_password.setFocusTraversalPolicyProvider(true);
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        panel_login.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 238, 230, 30));
        panel_login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 136, 50, 10));

        Boton_iniciae_sesion.setBackground(new java.awt.Color(243, 207, 212));
        Boton_iniciae_sesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Boton_iniciae_sesion.setText("Acceder");
        Boton_iniciae_sesion.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        Boton_iniciae_sesion.setBorderPainted(false);
        Boton_iniciae_sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_iniciae_sesion.setFocusPainted(false);
        Boton_iniciae_sesion.setFocusable(false);
        Boton_iniciae_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_iniciae_sesionActionPerformed(evt);
            }
        });
        panel_login.add(Boton_iniciae_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        label_IniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_IniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_IniciarSesion.setText("Iniciar Sesión");
        panel_login.add(label_IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 218, 38));

        jSeparator4.setForeground(java.awt.Color.black);
        jSeparator4.setName(""); // NOI18N
        panel_login.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 10));

        jSeparator5.setForeground(java.awt.Color.black);
        jSeparator5.setName(""); // NOI18N
        panel_login.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 230, 10));

        javax.swing.GroupLayout panel_derechaLayout = new javax.swing.GroupLayout(panel_derecha);
        panel_derecha.setLayout(panel_derechaLayout);
        panel_derechaLayout.setHorizontalGroup(
            panel_derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_derechaLayout.createSequentialGroup()
                .addGroup(panel_derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_derechaLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_derechaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_derechaLayout.setVerticalGroup(
            panel_derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_derechaLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        panel_background.add(panel_derecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 480));

        panel_izquierda.setBackground(java.awt.Color.white);
        panel_izquierda.setForeground(new java.awt.Color(255, 255, 255));
        panel_izquierda.setDoubleBuffered(false);
        panel_izquierda.setEnabled(false);

        panel_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo_Fajas_Angully (2).png"))); // NOI18N
        panel_logo.setToolTipText("");
        panel_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel_logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_logo.setMaximumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout panel_izquierdaLayout = new javax.swing.GroupLayout(panel_izquierda);
        panel_izquierda.setLayout(panel_izquierdaLayout);
        panel_izquierdaLayout.setHorizontalGroup(
            panel_izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_izquierdaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panel_izquierdaLayout.setVerticalGroup(
            panel_izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_izquierdaLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        panel_background.add(panel_izquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 350, 480));

        background.add(panel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 480));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_iniciae_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_iniciae_sesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_iniciae_sesionActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new login().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_iniciae_sesion;
    private javax.swing.JPanel background;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel label_IniciarSesion;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_usuario;
    private javax.swing.JPanel panel_background;
    private javax.swing.JPanel panel_derecha;
    private javax.swing.JPanel panel_izquierda;
    private javax.swing.JPanel panel_login;
    private javax.swing.JLabel panel_logo;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
