/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author TOR
 */
public class InternalFrame_NuevoProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrame_nuevoUsuario
     */
    public InternalFrame_NuevoProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_backgrounf = new javax.swing.JPanel();
        panel_datos_Usuario = new javax.swing.JPanel();
        Label_nombreProducto = new javax.swing.JLabel();
        label_idProducto = new javax.swing.JLabel();
        label_stockProducto = new javax.swing.JLabel();
        label_rolUsuario = new javax.swing.JLabel();
        label_nombreUsuarioSistema = new javax.swing.JLabel();
        label_lineaProducto = new javax.swing.JLabel();
        txt_idProducto = new javax.swing.JTextField();
        txt_nombreProducto = new javax.swing.JTextField();
        txt_stockProducto = new javax.swing.JTextField();
        txt_precioPorducto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        combox_Linea = new javax.swing.JComboBox<>();
        label_DescrictpcionProducto = new javax.swing.JLabel();
        label_tallaProducto = new javax.swing.JLabel();
        ComboBox_tallas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_descripcionProducto = new javax.swing.JTextArea();
        comboc_colores = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Nuevo Producto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_backgrounf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_nombreProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Label_nombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label_nombreProducto.setText("Nombre");

        label_idProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_idProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_idProducto.setText("ID Producto");

        label_stockProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_stockProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_stockProducto.setText("Stock");

        label_rolUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_rolUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_rolUsuario.setText("Precio");

        label_nombreUsuarioSistema.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_nombreUsuarioSistema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nombreUsuarioSistema.setText("Color");

        label_lineaProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_lineaProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_lineaProducto.setText("Linea");

        txt_idProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_nombreProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_stockProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_precioPorducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_precioPorducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioPorductoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton1.setText("Guardar");

        combox_Linea.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        combox_Linea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Romántica", "Powernet", "Comfort", "Deportiva", "Postquirúrgica" }));
        combox_Linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_LineaActionPerformed(evt);
            }
        });

        label_DescrictpcionProducto.setText("Decripción");

        label_tallaProducto.setText("Talla");

        ComboBox_tallas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ComboBox_tallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L", "XL", "2XL", "3XL" }));

        txtArea_descripcionProducto.setColumns(20);
        txtArea_descripcionProducto.setRows(5);
        jScrollPane1.setViewportView(txtArea_descripcionProducto);

        comboc_colores.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboc_colores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cocoa", "Negro", "Beige" }));

        javax.swing.GroupLayout panel_datos_UsuarioLayout = new javax.swing.GroupLayout(panel_datos_Usuario);
        panel_datos_Usuario.setLayout(panel_datos_UsuarioLayout);
        panel_datos_UsuarioLayout.setHorizontalGroup(
            panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(label_rolUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_nombreUsuarioSistema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(label_stockProducto)
                    .addComponent(Label_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_idProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addComponent(txt_nombreProducto)
                        .addComponent(txt_stockProducto)
                        .addComponent(txt_precioPorducto))
                    .addComponent(comboc_colores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                        .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label_DescrictpcionProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_tallaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBox_tallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                        .addComponent(label_lineaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combox_Linea, 0, 168, Short.MAX_VALUE)
                        .addGap(99, 99, 99))))
            .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_datos_UsuarioLayout.setVerticalGroup(
            panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_idProducto)
                    .addComponent(txt_idProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_DescrictpcionProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                        .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_nombreProducto)
                            .addComponent(txt_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_stockProducto)
                            .addComponent(txt_stockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_rolUsuario)
                            .addComponent(txt_precioPorducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_tallaProducto)
                            .addComponent(ComboBox_tallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_nombreUsuarioSistema)
                        .addComponent(comboc_colores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_lineaProducto)
                        .addComponent(combox_Linea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_backgrounf.add(panel_datos_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 300));

        getContentPane().add(panel_backgrounf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_precioPorductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioPorductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioPorductoActionPerformed

    private void combox_LineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_LineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combox_LineaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_tallas;
    private javax.swing.JLabel Label_nombreProducto;
    private javax.swing.JComboBox<String> comboc_colores;
    private javax.swing.JComboBox<String> combox_Linea;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_DescrictpcionProducto;
    private javax.swing.JLabel label_idProducto;
    private javax.swing.JLabel label_lineaProducto;
    private javax.swing.JLabel label_nombreUsuarioSistema;
    private javax.swing.JLabel label_rolUsuario;
    private javax.swing.JLabel label_stockProducto;
    private javax.swing.JLabel label_tallaProducto;
    private javax.swing.JPanel panel_backgrounf;
    private javax.swing.JPanel panel_datos_Usuario;
    private javax.swing.JTextArea txtArea_descripcionProducto;
    private javax.swing.JTextField txt_idProducto;
    private javax.swing.JTextField txt_nombreProducto;
    private javax.swing.JTextField txt_precioPorducto;
    private javax.swing.JTextField txt_stockProducto;
    // End of variables declaration//GEN-END:variables
}
