/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author TOR
 */
public class InternalFrame_GestionarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrame_GestionarUsuarios
     */
    public InternalFrame_GestionarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondoGestionarUsuarios = new javax.swing.JPanel();
        panelGestionUsuario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_GestionUsuarios = new javax.swing.JTable();
        panel_BotonesGestionUsuarios = new javax.swing.JPanel();
        botton_actualizar_datosCliente = new javax.swing.JButton();
        botton_eliminarCliente = new javax.swing.JButton();
        mostrar_mostrarDatos = new javax.swing.JPanel();
        label_nombreCliente = new javax.swing.JLabel();
        label_apellidoCliente = new javax.swing.JLabel();
        txt_nombre_Cliente = new javax.swing.JTextField();
        txt_apellido_Cliente = new javax.swing.JTextField();
        label_documentoIdentidadCliente = new javax.swing.JLabel();
        label_correoCliente = new javax.swing.JLabel();
        txt_documentoIdentidad_Cliente = new javax.swing.JTextField();
        txt_correo_Cliente = new javax.swing.JTextField();
        label_dirreción = new javax.swing.JLabel();
        txt_dirrecion_Cliente = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gesrionar Clientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_fondoGestionarUsuarios.setBackground(java.awt.Color.white);
        panel_fondoGestionarUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGestionUsuario.setBackground(new java.awt.Color(255, 255, 255));
        panelGestionUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_GestionUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabel_GestionUsuarios.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tabel_GestionUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Documento Identidad", "correo", "Dirreción", "Teléfono"
            }
        ));
        jScrollPane1.setViewportView(tabel_GestionUsuarios);

        panelGestionUsuario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 290));

        panel_fondoGestionarUsuarios.add(panelGestionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 570, 310));

        panel_BotonesGestionUsuarios.setBackground(new java.awt.Color(255, 255, 255));

        botton_actualizar_datosCliente.setText("Actualizar");
        botton_actualizar_datosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_actualizar_datosClienteActionPerformed(evt);
            }
        });

        botton_eliminarCliente.setText("Eliminar");

        javax.swing.GroupLayout panel_BotonesGestionUsuariosLayout = new javax.swing.GroupLayout(panel_BotonesGestionUsuarios);
        panel_BotonesGestionUsuarios.setLayout(panel_BotonesGestionUsuariosLayout);
        panel_BotonesGestionUsuariosLayout.setHorizontalGroup(
            panel_BotonesGestionUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BotonesGestionUsuariosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panel_BotonesGestionUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botton_actualizar_datosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botton_eliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panel_BotonesGestionUsuariosLayout.setVerticalGroup(
            panel_BotonesGestionUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BotonesGestionUsuariosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(botton_actualizar_datosCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botton_eliminarCliente)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panel_fondoGestionarUsuarios.add(panel_BotonesGestionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 160, -1));

        mostrar_mostrarDatos.setBackground(new java.awt.Color(255, 255, 255));

        label_nombreCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_nombreCliente.setText("Nombre");

        label_apellidoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_apellidoCliente.setText("Apellido");

        label_documentoIdentidadCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_documentoIdentidadCliente.setText("Documento Identidad");

        label_correoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_correoCliente.setText("Correo");

        txt_documentoIdentidad_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_documentoIdentidad_ClienteActionPerformed(evt);
            }
        });

        label_dirreción.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_dirreción.setText("Dirección");

        javax.swing.GroupLayout mostrar_mostrarDatosLayout = new javax.swing.GroupLayout(mostrar_mostrarDatos);
        mostrar_mostrarDatos.setLayout(mostrar_mostrarDatosLayout);
        mostrar_mostrarDatosLayout.setHorizontalGroup(
            mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrar_mostrarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mostrar_mostrarDatosLayout.createSequentialGroup()
                        .addComponent(label_nombreCliente)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nombre_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mostrar_mostrarDatosLayout.createSequentialGroup()
                        .addComponent(label_apellidoCliente)
                        .addGap(18, 18, 18)
                        .addComponent(txt_apellido_Cliente)))
                .addGap(30, 30, 30)
                .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_documentoIdentidadCliente)
                    .addComponent(label_correoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_documentoIdentidad_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_correo_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(label_dirreción)
                .addGap(30, 30, 30)
                .addComponent(txt_dirrecion_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        mostrar_mostrarDatosLayout.setVerticalGroup(
            mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrar_mostrarDatosLayout.createSequentialGroup()
                .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nombreCliente)
                    .addComponent(txt_nombre_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_documentoIdentidadCliente)
                    .addComponent(txt_documentoIdentidad_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_dirreción)
                    .addComponent(txt_dirrecion_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(mostrar_mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_apellidoCliente)
                    .addComponent(txt_apellido_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_correoCliente)
                    .addComponent(txt_correo_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        panel_fondoGestionarUsuarios.add(mostrar_mostrarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 800, 110));

        getContentPane().add(panel_fondoGestionarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 810, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botton_actualizar_datosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_actualizar_datosClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_actualizar_datosClienteActionPerformed

    private void txt_documentoIdentidad_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_documentoIdentidad_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_documentoIdentidad_ClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botton_actualizar_datosCliente;
    private javax.swing.JButton botton_eliminarCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_apellidoCliente;
    private javax.swing.JLabel label_correoCliente;
    private javax.swing.JLabel label_dirreción;
    private javax.swing.JLabel label_documentoIdentidadCliente;
    private javax.swing.JLabel label_nombreCliente;
    private javax.swing.JPanel mostrar_mostrarDatos;
    private javax.swing.JPanel panelGestionUsuario;
    private javax.swing.JPanel panel_BotonesGestionUsuarios;
    private javax.swing.JPanel panel_fondoGestionarUsuarios;
    private javax.swing.JTable tabel_GestionUsuarios;
    private javax.swing.JTextField txt_apellido_Cliente;
    private javax.swing.JTextField txt_correo_Cliente;
    private javax.swing.JTextField txt_dirrecion_Cliente;
    private javax.swing.JTextField txt_documentoIdentidad_Cliente;
    private javax.swing.JTextField txt_nombre_Cliente;
    // End of variables declaration//GEN-END:variables
}
