/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author TOR
 */
public class InternalFrame_nuevoCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrame_nuevoUsuario
     */
    public InternalFrame_nuevoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_backgrounf = new javax.swing.JPanel();
        panel_datos_Usuario = new javax.swing.JPanel();
        Label_nombreCliente = new javax.swing.JLabel();
        label_apellidoCliente = new javax.swing.JLabel();
        label_documentoIdentidadCliente = new javax.swing.JLabel();
        label_correoCliente = new javax.swing.JLabel();
        label_contraseñaCliente = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        txt_apellidoCliente = new javax.swing.JTextField();
        txt_documentoIdentidadCliente = new javax.swing.JTextField();
        txt_correoCliente = new javax.swing.JTextField();
        txt_direccionCliente = new javax.swing.JTextField();
        botton_guardarDatosCliente = new javax.swing.JButton();
        label_telefonoCliente = new javax.swing.JLabel();
        txt_telefonoCliente = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Nuevo Cliente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_backgrounf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_datos_Usuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        Label_nombreCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Label_nombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label_nombreCliente.setText("Nombre");

        label_apellidoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_apellidoCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_apellidoCliente.setText("Apellido");

        label_documentoIdentidadCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_documentoIdentidadCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_documentoIdentidadCliente.setText("Documento Identidad");

        label_correoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_correoCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_correoCliente.setText("Correo");

        label_contraseñaCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_contraseñaCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_contraseñaCliente.setText("Dirección");

        txt_nombreCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_apellidoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_documentoIdentidadCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_correoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_direccionCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        botton_guardarDatosCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        botton_guardarDatosCliente.setText("Guardar");
        botton_guardarDatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botton_guardarDatosClienteActionPerformed(evt);
            }
        });

        label_telefonoCliente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_telefonoCliente.setText("Teléfono");

        javax.swing.GroupLayout panel_datos_UsuarioLayout = new javax.swing.GroupLayout(panel_datos_Usuario);
        panel_datos_Usuario.setLayout(panel_datos_UsuarioLayout);
        panel_datos_UsuarioLayout.setHorizontalGroup(
            panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(label_correoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_contraseñaCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Label_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_documentoIdentidadCliente)
                    .addComponent(label_telefonoCliente))
                .addGap(72, 72, 72)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botton_guardarDatosCliente)
                    .addComponent(txt_nombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(txt_apellidoCliente)
                    .addComponent(txt_documentoIdentidadCliente)
                    .addComponent(txt_correoCliente)
                    .addComponent(txt_direccionCliente)
                    .addComponent(txt_telefonoCliente))
                .addGap(119, 119, 119))
        );
        panel_datos_UsuarioLayout.setVerticalGroup(
            panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_nombreCliente)
                    .addComponent(txt_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_apellidoCliente)
                    .addComponent(txt_apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_documentoIdentidadCliente)
                    .addComponent(txt_documentoIdentidadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_correoCliente)
                    .addComponent(txt_correoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_contraseñaCliente)
                    .addComponent(txt_direccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_telefonoCliente)
                    .addComponent(txt_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(botton_guardarDatosCliente)
                .addContainerGap())
        );

        panel_backgrounf.add(panel_datos_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 310));

        getContentPane().add(panel_backgrounf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botton_guardarDatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botton_guardarDatosClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botton_guardarDatosClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_nombreCliente;
    private javax.swing.JButton botton_guardarDatosCliente;
    private javax.swing.JLabel label_apellidoCliente;
    private javax.swing.JLabel label_contraseñaCliente;
    private javax.swing.JLabel label_correoCliente;
    private javax.swing.JLabel label_documentoIdentidadCliente;
    private javax.swing.JLabel label_telefonoCliente;
    private javax.swing.JPanel panel_backgrounf;
    private javax.swing.JPanel panel_datos_Usuario;
    private javax.swing.JTextField txt_apellidoCliente;
    private javax.swing.JTextField txt_correoCliente;
    private javax.swing.JTextField txt_direccionCliente;
    private javax.swing.JTextField txt_documentoIdentidadCliente;
    private javax.swing.JTextField txt_nombreCliente;
    private javax.swing.JTextField txt_telefonoCliente;
    // End of variables declaration//GEN-END:variables
}
