/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author TOR
 */
public class InternalFrame_NuevoUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrame_nuevoUsuario
     */
    public InternalFrame_NuevoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_backgrounf = new javax.swing.JPanel();
        panel_datos_Usuario = new javax.swing.JPanel();
        Label_nombreUsuario = new javax.swing.JLabel();
        label_apellidoUsuario = new javax.swing.JLabel();
        label_documentoIdentidadUsuario = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        label_rolUsuario = new javax.swing.JLabel();
        label_nombreUsuarioSistema = new javax.swing.JLabel();
        label_contraseñaUsuarioSistema = new javax.swing.JLabel();
        txt_nombreUsuario = new javax.swing.JTextField();
        txt_apellidoUsuario = new javax.swing.JTextField();
        txt_documentoIdentidadUsuario = new javax.swing.JTextField();
        txt_nombreUsuarioSistema = new javax.swing.JTextField();
        txt_contraseñaUsuarioSistema = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Nuevo Usuario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_backgrounf.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_nombreUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Label_nombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label_nombreUsuario.setText("Nombre");

        label_apellidoUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_apellidoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_apellidoUsuario.setText("Apellido");

        label_documentoIdentidadUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_documentoIdentidadUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_documentoIdentidadUsuario.setText("Documento Identidad");

        jComboBox1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        label_rolUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_rolUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_rolUsuario.setText("Rol");

        label_nombreUsuarioSistema.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_nombreUsuarioSistema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nombreUsuarioSistema.setText("Nombre Usuario");

        label_contraseñaUsuarioSistema.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        label_contraseñaUsuarioSistema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_contraseñaUsuarioSistema.setText("Contraseña");

        txt_nombreUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_apellidoUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_documentoIdentidadUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_nombreUsuarioSistema.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txt_contraseñaUsuarioSistema.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton1.setText("Guardar");

        javax.swing.GroupLayout panel_datos_UsuarioLayout = new javax.swing.GroupLayout(panel_datos_Usuario);
        panel_datos_Usuario.setLayout(panel_datos_UsuarioLayout);
        panel_datos_UsuarioLayout.setHorizontalGroup(
            panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(label_rolUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_nombreUsuarioSistema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_contraseñaUsuarioSistema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Label_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_apellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_documentoIdentidadUsuario))
                .addGap(72, 72, 72)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_nombreUsuario)
                        .addComponent(txt_apellidoUsuario)
                        .addComponent(txt_documentoIdentidadUsuario)
                        .addComponent(txt_nombreUsuarioSistema)
                        .addComponent(txt_contraseñaUsuarioSistema, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                .addGap(119, 119, 119))
        );
        panel_datos_UsuarioLayout.setVerticalGroup(
            panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_UsuarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_nombreUsuario)
                    .addComponent(txt_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_apellidoUsuario)
                    .addComponent(txt_apellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_documentoIdentidadUsuario)
                    .addComponent(txt_documentoIdentidadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_rolUsuario)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nombreUsuarioSistema)
                    .addComponent(txt_nombreUsuarioSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_datos_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_contraseñaUsuarioSistema)
                    .addComponent(txt_contraseñaUsuarioSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        panel_backgrounf.add(panel_datos_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 360));

        getContentPane().add(panel_backgrounf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_nombreUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel label_apellidoUsuario;
    private javax.swing.JLabel label_contraseñaUsuarioSistema;
    private javax.swing.JLabel label_documentoIdentidadUsuario;
    private javax.swing.JLabel label_nombreUsuarioSistema;
    private javax.swing.JLabel label_rolUsuario;
    private javax.swing.JPanel panel_backgrounf;
    private javax.swing.JPanel panel_datos_Usuario;
    private javax.swing.JTextField txt_apellidoUsuario;
    private javax.swing.JTextField txt_contraseñaUsuarioSistema;
    private javax.swing.JTextField txt_documentoIdentidadUsuario;
    private javax.swing.JTextField txt_nombreUsuario;
    private javax.swing.JTextField txt_nombreUsuarioSistema;
    // End of variables declaration//GEN-END:variables
}
