/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author TOR
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_izquierda = new javax.swing.JPanel();
        panel_logo = new javax.swing.JLabel();
        panel_derecha = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panel_login = new javax.swing.JPanel();
        label_usuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        txt_contraseña = new javax.swing.JPasswordField();
        Boton_iniciae_sesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_izquierda.setBackground(java.awt.Color.white);
        panel_izquierda.setForeground(new java.awt.Color(255, 255, 255));
        panel_izquierda.setDoubleBuffered(false);
        panel_izquierda.setEnabled(false);

        panel_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo_Fajas_Angully (2).png"))); // NOI18N
        panel_logo.setToolTipText("");
        panel_logo.setMaximumSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout panel_izquierdaLayout = new javax.swing.GroupLayout(panel_izquierda);
        panel_izquierda.setLayout(panel_izquierdaLayout);
        panel_izquierdaLayout.setHorizontalGroup(
            panel_izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_izquierdaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_izquierdaLayout.setVerticalGroup(
            panel_izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_izquierdaLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(panel_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        getContentPane().add(panel_izquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 480));

        panel_derecha.setBackground(new java.awt.Color(242, 206, 211));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        panel_login.setOpaque(false);

        label_usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_usuario.setForeground(java.awt.Color.white);
        label_usuario.setText("Usuario");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Constraseña");

        Boton_iniciae_sesion.setBackground(java.awt.Color.pink);
        Boton_iniciae_sesion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Boton_iniciae_sesion.setText("Iniciar Sesión");
        Boton_iniciae_sesion.setBorder(null);
        Boton_iniciae_sesion.setBorderPainted(false);
        Boton_iniciae_sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_iniciae_sesion.setFocusPainted(false);
        Boton_iniciae_sesion.setFocusable(false);
        Boton_iniciae_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_iniciae_sesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txt_usuario)
                    .addComponent(txt_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                        .addComponent(Boton_iniciae_sesion)
                        .addGap(19, 19, 19)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(label_usuario)
                .addGap(18, 18, 18)
                .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(Boton_iniciae_sesion)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout panel_derechaLayout = new javax.swing.GroupLayout(panel_derecha);
        panel_derecha.setLayout(panel_derechaLayout);
        panel_derechaLayout.setHorizontalGroup(
            panel_derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_derechaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_derechaLayout.setVerticalGroup(
            panel_derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_derechaLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(panel_derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_derechaLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_derechaLayout.createSequentialGroup()
                        .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );

        getContentPane().add(panel_derecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 340, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_iniciae_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_iniciae_sesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_iniciae_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new login().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_iniciae_sesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_usuario;
    private javax.swing.JPanel panel_derecha;
    private javax.swing.JPanel panel_izquierda;
    private javax.swing.JPanel panel_login;
    private javax.swing.JLabel panel_logo;
    private javax.swing.JPasswordField txt_contraseña;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
