/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author TOR
 */
public class view_Menu extends javax.swing.JFrame {

    /**
     * Creates new form view_Gestion
     */
    public view_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background_Gestion = new javax.swing.JPanel();
        panel_Gestion = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_nuevo_Usuario = new javax.swing.JMenuItem();
        jMenuItem_Gestionar_Usuarios = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem_nuevo_Cliente = new javax.swing.JMenuItem();
        jMenuItem_buscar_cliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_nuevo_Producto = new javax.swing.JMenuItem();
        jMenuItem_Gestion_Producto = new javax.swing.JMenuItem();
        jMenuItem_buscar_Producto = new javax.swing.JMenuItem();
        jMenuItem_eliminar_Producto = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem_nueva_Linea = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem_nuevo_proveedor = new javax.swing.JMenuItem();
        jMenuItem_gestinoar_proveedores = new javax.swing.JMenuItem();
        jMenuItem_eliminar_proveedor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_nueva_venta = new javax.swing.JMenuItem();
        jMenuItem_gestionar_venta = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem_reporte_Linea = new javax.swing.JMenuItem();
        jMenuItem_reporte_proveedor = new javax.swing.JMenuItem();
        jMenuItem_reporte_producto = new javax.swing.JMenuItem();
        jMenuItem_reporte_venta = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem_historial_ventas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_cerrar_sesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setEnabled(false);
        setFocusCycleRoot(false);
        setFocusable(false);
        setFocusableWindowState(false);
        setForeground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background_Gestion.setBackground(java.awt.Color.white);
        background_Gestion.setFocusable(false);
        background_Gestion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Gestion.setBackground(new java.awt.Color(255, 255, 255));
        panel_Gestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_Gestion.setMaximumSize(new java.awt.Dimension(150, 50));
        panel_Gestion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        background_Gestion.add(panel_Gestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 570));

        getContentPane().add(background_Gestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 630));

        jMenuBar1.setBorder(null);
        jMenuBar1.setBorderPainted(false);

        jMenu2.setBorder(null);
        jMenu2.setText("Usuario");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setMinimumSize(new java.awt.Dimension(130, 50));
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_nuevo_Usuario.setText("Nuevo Usuario");
        jMenuItem_nuevo_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_nuevo_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_nuevo_Usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.add(jMenuItem_nuevo_Usuario);

        jMenuItem_Gestionar_Usuarios.setText("Gestionar Usuarios");
        jMenuItem_Gestionar_Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_Gestionar_Usuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_Gestionar_Usuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_Gestionar_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Gestionar_UsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Gestionar_Usuarios);

        jMenuBar1.add(jMenu2);

        jMenu10.setBorder(null);
        jMenu10.setText("Cliente");
        jMenu10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jMenu10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenuItem_nuevo_Cliente.setText("Nuevo Cliente");
        jMenuItem_nuevo_Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_nuevo_Cliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_nuevo_Cliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu10.add(jMenuItem_nuevo_Cliente);

        jMenuItem_buscar_cliente.setText("Gestionar Clientes");
        jMenuItem_buscar_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_buscar_cliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_buscar_cliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu10.add(jMenuItem_buscar_cliente);

        jMenuBar1.add(jMenu10);

        jMenu3.setBorder(null);
        jMenu3.setText("Producto");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_nuevo_Producto.setText("Nuevo Producto");
        jMenuItem_nuevo_Producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_nuevo_Producto.setHideActionText(true);
        jMenuItem_nuevo_Producto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_nuevo_Producto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.add(jMenuItem_nuevo_Producto);

        jMenuItem_Gestion_Producto.setText("Gestion Producto");
        jMenuItem_Gestion_Producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_Gestion_Producto.setHideActionText(true);
        jMenuItem_Gestion_Producto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_Gestion_Producto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.add(jMenuItem_Gestion_Producto);

        jMenuItem_buscar_Producto.setText("Buscar Producto");
        jMenuItem_buscar_Producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_buscar_Producto.setHideActionText(true);
        jMenuItem_buscar_Producto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_buscar_Producto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.add(jMenuItem_buscar_Producto);

        jMenuItem_eliminar_Producto.setText("Eliminar Producto");
        jMenuItem_eliminar_Producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_eliminar_Producto.setHideActionText(true);
        jMenuItem_eliminar_Producto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_eliminar_Producto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.add(jMenuItem_eliminar_Producto);

        jMenuBar1.add(jMenu3);

        jMenu5.setBorder(null);
        jMenu5.setText("Linea");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu5.setMinimumSize(new java.awt.Dimension(140, 50));
        jMenu5.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_nueva_Linea.setText("Nueva Linea");
        jMenuItem_nueva_Linea.setBorder(null);
        jMenuItem_nueva_Linea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_nueva_Linea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_nueva_Linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_nueva_Linea.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu5.add(jMenuItem_nueva_Linea);

        jMenuItem11.setText("Gestión de Lineas");
        jMenuItem11.setBorder(null);
        jMenuItem11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        jMenu8.setBorder(null);
        jMenu8.setText("Proveedor");
        jMenu8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jMenu8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu8.setMinimumSize(new java.awt.Dimension(70, 15));

        jMenuItem_nuevo_proveedor.setText("Nuevo proveedor");
        jMenuItem_nuevo_proveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_nuevo_proveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_nuevo_proveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_nuevo_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevo_proveedorActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem_nuevo_proveedor);

        jMenuItem_gestinoar_proveedores.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jMenuItem_gestinoar_proveedores.setText("Gestionar Proveedores");
        jMenuItem_gestinoar_proveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_gestinoar_proveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu8.add(jMenuItem_gestinoar_proveedores);

        jMenuItem_eliminar_proveedor.setText("Eliminar Proveedor");
        jMenuItem_eliminar_proveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_eliminar_proveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu8.add(jMenuItem_eliminar_proveedor);

        jMenuBar1.add(jMenu8);

        jMenu4.setBorder(null);
        jMenu4.setText("Factura");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu4.setMaximumSize(new java.awt.Dimension(120, 32767));
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 40));

        jMenuItem_nueva_venta.setText("Nueva Venta");
        jMenuItem_nueva_venta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_nueva_venta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu4.add(jMenuItem_nueva_venta);

        jMenuItem_gestionar_venta.setText("Gestionar Venta");
        jMenuItem_gestionar_venta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_gestionar_venta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_gestionar_venta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuItem_gestionar_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gestionar_ventaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_gestionar_venta);

        jMenuBar1.add(jMenu4);

        jMenu9.setBorder(null);
        jMenu9.setText("Reportes");
        jMenu9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jMenu9.setHideActionText(true);
        jMenu9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu9.setMinimumSize(new java.awt.Dimension(60, 15));

        jMenuItem_reporte_Linea.setText("Reporte Linea");
        jMenuItem_reporte_Linea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_reporte_Linea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_reporte_Linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu9.add(jMenuItem_reporte_Linea);

        jMenuItem_reporte_proveedor.setText("Reporte Proveedor");
        jMenuItem_reporte_proveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_reporte_proveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu9.add(jMenuItem_reporte_proveedor);

        jMenuItem_reporte_producto.setText("Reporte Producto");
        jMenuItem_reporte_producto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_reporte_producto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu9.add(jMenuItem_reporte_producto);

        jMenuItem_reporte_venta.setText("Reporte Venta");
        jMenuItem_reporte_venta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_reporte_venta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu9.add(jMenuItem_reporte_venta);

        jMenuBar1.add(jMenu9);

        jMenu7.setBorder(null);
        jMenu7.setText("Historial");
        jMenu7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jMenu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu7.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_historial_ventas.setText("Ventas ");
        jMenuItem_historial_ventas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem_historial_ventas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenuItem_historial_ventas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu7.add(jMenuItem_historial_ventas);

        jMenuBar1.add(jMenu7);

        jMenu6.setBorder(null);
        jMenu6.setText("Cerrar Sesión");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jMenu6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_cerrar_sesion.setText("Cerrar Sesión");
        jMenu6.add(jMenuItem_cerrar_sesion);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("frferf");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_Gestionar_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Gestionar_UsuariosActionPerformed
       

    }//GEN-LAST:event_jMenuItem_Gestionar_UsuariosActionPerformed

    private void jMenuItem_nuevo_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevo_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_nuevo_proveedorActionPerformed

    private void jMenuItem_gestionar_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gestionar_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_gestionar_ventaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background_Gestion;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem_Gestion_Producto;
    private javax.swing.JMenuItem jMenuItem_Gestionar_Usuarios;
    private javax.swing.JMenuItem jMenuItem_buscar_Producto;
    private javax.swing.JMenuItem jMenuItem_buscar_cliente;
    private javax.swing.JMenuItem jMenuItem_cerrar_sesion;
    private javax.swing.JMenuItem jMenuItem_eliminar_Producto;
    private javax.swing.JMenuItem jMenuItem_eliminar_proveedor;
    private javax.swing.JMenuItem jMenuItem_gestinoar_proveedores;
    private javax.swing.JMenuItem jMenuItem_gestionar_venta;
    private javax.swing.JMenuItem jMenuItem_historial_ventas;
    private javax.swing.JMenuItem jMenuItem_nueva_Linea;
    private javax.swing.JMenuItem jMenuItem_nueva_venta;
    private javax.swing.JMenuItem jMenuItem_nuevo_Cliente;
    private javax.swing.JMenuItem jMenuItem_nuevo_Producto;
    private javax.swing.JMenuItem jMenuItem_nuevo_Usuario;
    private javax.swing.JMenuItem jMenuItem_nuevo_proveedor;
    private javax.swing.JMenuItem jMenuItem_reporte_Linea;
    private javax.swing.JMenuItem jMenuItem_reporte_producto;
    private javax.swing.JMenuItem jMenuItem_reporte_proveedor;
    private javax.swing.JMenuItem jMenuItem_reporte_venta;
    private javax.swing.JPanel panel_Gestion;
    // End of variables declaration//GEN-END:variables
}
